### ISSUE TITLE
Problem with function in context

### ISSUE THREAD

**Issue by fleskberg** [MTobisch/ngx-dynamic-hooks#30]
Hi! I have encountered a problem with using event emitter with function in context in dynamic hooks.
I figured that it perhaps was a bit problematic to describe the problem with so I created an example project with similar issue. 
[dynamic-hook-example.zip](https://github.com/MTobisch/ngx-dynamic-hooks/files/10978395/dynamic-hook-example.zip)

**Comment by MTobisch** [comment]
Thanks for making me aware of this, once again. Feels like half the bugs resolved so far are due to you bringing them to my attention :-]

Anywhere, I think this is fixed now. Give it a shot:

**Angular 6-13:** ngx-dynamic-hooks 1.7.6
**Angular 13+:** ngx-dynamic-hooks 2.0.6

**Bug explanation:** When parsing context expressions from the dynamic string, I somewhat needlessly de/serialized nested expressions/variables, such as the `$event` parameter in your example `context.testFunction.emit($event)`. Not normally a big deal with primitives and simple types, but as the `$event` parameter contained a function and functions can't be de/serialized via JSON.stringfy, it was removed instead, hence the empty object. 

Due to the same bug, you could also run into similar problems if you used nested context variables like `context.method(context.someParam)` and context.someParam was unserializable (for example due to being a Map object), so its a good thing you discovered this. Thanks!

**Comment by fleskberg** [comment]
Hi, work better now. Thanks! However we found another thing that was a little bit strange, we see some issues when emitting from OnDestroy when using dynamic hooks, but it works when we don´t. Can you help us?
[dynamic-hook-on-destroy.zip](https://github.com/MTobisch/ngx-dynamic-hooks/files/11012026/dynamic-hook-on-destroy.zip)

**Comment by fleskberg** [comment]
@MTobisch I´m so used to get a response the same day as i raise a question from you, that I wonder if you missed my other question? :D

**Comment by MTobisch** [comment]
Hey there,

yeah sorry, I've been a bit busy. I've already looked at the problem though and know what causes it. I'm planning to implement the fix in the next days.

If its a pressing issue, here's how you can fix it youself in the meantime:

Go into

`yourProject/node_modules/ngx-dynamic-hooks/fesm2020/ngx-dynamic-hooks.mjs` 

It may not use `fesm2020` for you but one of the other folders, so you might have to try around a bit.

Search in the file for "destroy" to find the `OutletService.destroy()` method. Its not long and by having a glance at it, you can probably already tell the problem. It unsubscribes from component outputs before destroying them (triggering ngOnDestroy). To fix this, simply swap the places of the two code block so it destroys components before unsubscribing.

Obviously, this is a flaky fix and reinstalling dependencies will overwrite it. But I hope its better than nothing for now.

**Comment by fleskberg** [comment]
Hi again! It´s not that much of a rush, just wanted to know if you noticed my question. It´s enough that we know that it will come a fix in a couple of days. Thanks alot for the response!

**Comment by MTobisch** [comment]
Alright then, here's the new version that includes the onDestroy-fix:

Angular 6-13: ngx-dynamic-hooks 1.8.0
Angular 13+: ngx-dynamic-hooks 2.1.0

Cheers!

**Comment by fleskberg** [comment]
Looks better now with 1.8.0, thank you!
